; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pro8MHzatmega328]
platform = atmelavr
board = ATmega328P
; No framework line here = Pure AVR-GCC

; Ensure the code knows it is running at 8MHz
board_build.f_cpu = 8000000L

; --- UART Upload Settings ---
upload_protocol = arduino
upload_port = /dev/cu.usbserial-D308HLRH 
upload_speed = 57600

monitor_speed = 9600 ;serial monitor to match chip's speed

; If you have multiple devices plugged in, tell it exactly which one to watch
; Replace with your actual port from 'ls /dev/cu.usb*'
monitor_port = /dev/cu.usbserial-D308HLRH
